### ISSUE TITLE
add AAT full integration test 

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#101]
same as with normal race, such that specific aat code is also tested
this comp can be used: http://www.soaringspot.com/en_gb/cae-nls-nederlandse-kampioenschappen-zweefvliegen-2012/results/combiklasse/task-10-on-2012-05-26/daily

**Comment by GliderGeek** [comment]
@roeles: can you help me out a little with how you added the other test?
what does the sha512 sum do?

**Comment by roeles** [comment]
The general idear is that you compare the sha512 checksum of a "validated" result with the result we generate during CI.
This is effectively a byte-for-byte comparison of the output files.

`sha512 FILE` produces a line which you can copy-paste in the Analysis_PySoar.xls.sha512 file, or use a new file in the ci directory.

https://github.com/GliderGeek/PySoar/blob/master/.travis.yml#L20
performs the checking, after CI has run the analysis.

**Comment by GliderGeek** [comment]
This can be done after #107

**Comment by GliderGeek** [comment]
covered in a854b04f3387b86ed0ac96eab87cc9a6a8f95d01
