### ISSUE TITLE
How to build an executable from the sources

### ISSUE THREAD

**Issue by hnpilot** [GliderGeek/PySoar#130]
Hi

I would like to create a new version for a competition in run. The problem is that pysoar (or rather opensoar) skips the HC pilots. I found the HC string in opensoar library for competitors to be eliminated, but I found no way to build the software.
I am quite familiar in programming and moderately so also in python, but haven't ever built anything as an executable (ie everything is command line so far) and the documentation of pysoar is (to say it gently) quite sparse especially in this regard ;)
I tried to utilize PyInstaller but couldn't figure out, what to put after the command (or yes, I did but I wouldn't like to give the embarrassing details out, as they didn't succeed). I am developing it on Windows 10 64-environment.
Would it be possible to provide small examples of the build process after the pip install that I eventually got working?
wbr hn

**Comment by GliderGeek** [comment]
There is a build script which can be run directly with python:
https://github.com/GliderGeek/PySoar/blob/master/PySoar/standalone/build.py

Simply run: `python build.py` in the folder.

The documentation is indeed very limited. Would you be willing to create a pull request for the necessary build steps?

**Comment by GliderGeek** [comment]
@hnpilot: did you manage to get an executable?

**Comment by hnpilot** [comment]
Sorry. Didn't have more time as we flew all the days after that ;) I will look at it next week..Wbr hannuSent from my Huawei Mobile-------- Original Message --------Subject: Re: [GliderGeek/PySoar] How to build an executable from the sources (#130)From: GliderGeek To: GliderGeek/PySoar CC: hnpilot ,Mention @hnpilot: did you manage to get an executable?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/GliderGeek/PySoar/issues/130#issuecomment-397807689","url":"https://github.com/GliderGeek/PySoar/issues/130#issuecomment-397807689","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GliderGeek/PySoar","title":"GliderGeek/PySoar","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/GliderGeek/PySoar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GliderGeek in #130: @hnpilot: did you manage to get an executable?"}],"action":{"name":"View Issue","url":"https://github.com/GliderGeek/PySoar/issues/130#issuecomment-397807689"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [GliderGeek/PySoar] How to build an executable from the sources (#130)",
"sections": [
{
"text": "",
"activityTitle": "**GliderGeek**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@GliderGeek",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"GliderGeek/PySoar\",\n\"issueId\": 130,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"GliderGeek/PySoar\",\n\"issueId\": 130\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/GliderGeek/PySoar/issues/130#issuecomment-397807689"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344621875\n}"
}
],
"themeColor": "26292E"
}

**Comment by GliderGeek** [comment]
@hnpilot : i'm thinking bout removing the filtering on HC pilots. can you give an example competition which i can use for testing?

**Comment by GliderGeek** [comment]
@hnpilot: i have added build instructions to the readme if you're interested.
