### ISSUE TITLE
Update standanlones versions

### ISSUE THREAD

**Issue by jkretz** [GliderGeek/PySoar#146]
Hello @GliderGeek,
would it be possible to update the standalones of PySoar to the newest version (that includes the fix for the scoringStrepla AATs in opensoar). I got some requests for the newest version from a few people but unfortunately, I struggle getting the build process of the binaries going.
Cheers,
Jan

**Comment by GliderGeek** [comment]
Dear Jan,
i would like to but i am running into problems as well, which held me back of deploying a new version.
will try again soon. have opened a branch which should build a windows version in appveyor, but the executable it produces does not seem to work. it might give a good direction though of how you can build the application.

will hopefully have time to fix this soon.

**Comment by jkretz** [comment]
Thanks for your efforts. Good to hear that it was not my stupidity alone.
Cheers,
Jan

GliderGeek <notifications@github.com> schrieb am Mi., 6. März 2019, 22:59:

**Comment by GliderGeek** [comment]
@jkretz: i have released a new version. furthermore i have added build instructions in the README.
