### ISSUE TITLE
Idea to reimplement soaringspot.com analysis

### ISSUE THREAD

**Issue by jkretz** [GliderGeek/PySoar#157]
Hi,
I think there might be a hacky way to get the soaringspot analysis running again. If you just download the html file of the respective flight on the daily scoring page (i.e. wget https://www.soaringspot.com/en_gb/download-contest-flight/*), the task information and the flight trace of the flight can be found in this file stored in kind of a dictionary, (search for  "window.__PRELOADED_STATE__" in the html). I think with a little reverse engineering, it might be possible to recreate the *.igc file from that as everything needed for the analysis can be found in there.
Cheers,
Jan

**Comment by GliderGeek** [comment]
nice! i tried to look for solutions in the html, but i am not very familiar with frontend code, so i was a bit lost. will give this a try

**Comment by GliderGeek** [comment]
i see that "window.PRELOADED_STATE" contains the parsed content of the IGC-file, which is pretty neat, but i would prefer to have the original IGC file, which is available under the download button. is it possible to obtain this without running a headless browser?

**Comment by jkretz** [comment]
Yes, it would definitely be the more elegant way to directly get the IGC file. Unfortunately, I am not an expert in that regard either and just did a little superficial try whether it is possible to somehow obtain the URL for the IGC file and ended up with this parsed version in the html. I think to directly obtain the IGC file, a headless browser is probably the way to go.

**Comment by jkretz** [comment]
For now, this should work to get the flight track and the task information into a python dictionary

import json
import requests
igc_url = 'https://www.soaringspot.com/en_gb/download-contest-flight/*'
html = str(requests.get(igc_url).content, encoding='latin')
start = 'window.__PRELOADED_STATE__ ='
end = ',"events":'
j = html[html.find(start) + len(start):]
j = j[:j.find(end)]+'}}}}' ### Not nice
j = json.loads(j)

**Comment by jkretz** [comment]
I had some time yesterday evening and wrote a script that does the HTML to IGC conversion. I have not tested it with opensoar yet but I think it should work in principle. Everything that is needed is included according to the opensoar/soaringspot standard. You can find my script here:
https://github.com/jkretz/soarinspot_fix
The only thing that worries me is that the html-to-json parsing could get quite tedious to maintain in the long run. The question is whether it makes sense to implement it like this into opensoar or if one should rather try to directly retrieve the IGC file.

**Comment by GliderGeek** [comment]
nice, i don't have the time to look at it right now, but will let you know when i do.

**Comment by GliderGeek** [comment]
@jkretz : great news: a teammember of the dutch national team has contacted naviter and fixed that the download links are back in the daily results page!

<img width="484" alt="image" src="https://user-images.githubusercontent.com/16109193/74423301-534b1080-4e50-11ea-88be-f0faaf6b83a5.png">

just have to figure out how to parse this out

**Comment by GliderGeek** [comment]
its quite trivial, here's the pull request: https://github.com/GliderGeek/opensoar/pull/33

**Comment by jkretz** [comment]
Really great news that that put the direct download links back. It is
definitely much better than what I proposed.
Just something else, the 0.60 windows build seems to be broken. It is not
working on my laptop and others have also reported that. Version 0.57.2 is
still functional, but I haven't checked the 0.59 yet.


Am Do., 13. Feb. 2020 um 12:02 Uhr schrieb GliderGeek <
notifications@github.com>:

**Comment by GliderGeek** [comment]
yeah i am aware of the broken build. personally i am on mac which makes it very difficult to correctly setup a CI script for travis to work with. do you have windows access by any chance?

**Comment by jkretz** [comment]
I use Linux and really rarely use windows and if so, I run it using VirtualBox, which is not really practical

**Comment by GliderGeek** [comment]
@jkretz : i created a new release which seems to be working on mac.
https://github.com/GliderGeek/PySoar/releases

however i have trouble setting up virtualbox on my mac so i cannot check the windows build.

could you help me out and check if the windows build works?

**Comment by jkretz** [comment]
@GliderGeek : Just checked the new build. As far as I have seen, everything is working. Nice work

**Comment by GliderGeek** [comment]
Awesome

**Comment by GliderGeek** [comment]
done
