### ISSUE TITLE
link to excel file in gui

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#30]
after analysis, there should be an icon to be clicked which leads you to the folder in which the excel sheet is placed.

**Comment by roeles** [comment]
Why  not open the file directly? Libre Office for Linux, Windows has a
command to open a file in the standard application as if you double-click
the file.
Op 16 dec. 2015 14:55 schreef "GliderGeek" <notifications@github.com>:

**Comment by GliderGeek** [comment]
good point, this would be preferable.

**Comment by roeles** [comment]
In Windows you can just use os.system("filename.xls"), in my experience.

Roel

**Comment by GliderGeek** [comment]
implemented in last commit
