### ISSUE TITLE
Version number in PySoar

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#66]
it is handy to enable a comparison between the releases page on GH and a version number in the software to check whether you have the most recent version.

**Comment by roeles** [comment]
Why not just git pull and make sure you have the latest version? Is
checking significantly cheaper than enforcing?

Op do 21 jul. 2016 13:25 schreef GliderGeek <notifications@github.com>:

**Comment by GliderGeek** [comment]
this is mainly for people who already have pysoar downloaded. when they check the release page, there is no simple way to compare the latest release version with their downloaded one
