### ISSUE TITLE
analysis breaks: corrupt file

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#94]
http://www.soaringspot.com/en_gb/nationale-junioren-wedstrijd-2015-venlose-zweefvliegclub-2015/results/open/task-3-on-2015-08-03/daily

cause: corrupt file D3.igc

**Comment by roeles** [comment]
I would like to suggest that you add this test to your .travis.yml file as part of fixing this bug.
This not only proves that you solved the bug, but it also adds meaningful test cases for your code. You will never introduce this bug again without knowing.

**Comment by GliderGeek** [comment]
good suggestion roel.

**Comment by GliderGeek** [comment]
regarding the specifics of the bug: the problem comes from a corrupt igc file:
http://archive.soaringspot.com/contest/016/1647/flights/3090/3240099895.igc
any ideas on how to detect this?

**Comment by roeles** [comment]
I'll try to look at it today and come up with a suggestion.

**Comment by roeles** [comment]
I would suggest that you somehow ignore the entire line in
flightClass.py:52

**Comment by GliderGeek** [comment]
this will be solved when switching to aerofiles igc reader
this reader is able to ensure that the b-records are valid

**Comment by GliderGeek** [comment]
has been fixed in commit https://github.com/GliderGeek/opensoar/commit/d9366c101564d099cbf675b37d4df7b485002ad7
