### ISSUE TITLE
When pygeodesy is not found, suggest git clone --recursive

### ISSUE THREAD

**Issue by roeles** [GliderGeek/PySoar#95]
When pygeodesy is not found, this could be due to not using the `--recursive` flag during `git clone`
Instead of printing a stacktrace, it might be better to error neatly when this happens.

**Comment by GliderGeek** [comment]
i do not really follow what you mean. can you explain a bit more?

not sure if i want to take actions on pygeodesy as it will be available on pip in [not too long](https://github.com/mrJean1/PyGeodesy/issues/2), so it will become a regular dependency in the `requirements.txt` file

**Comment by roeles** [comment]
When I don't clone your repository on the commandline with the `--recursive` flag, submodules are not cloned as well.
This leaves the directory where pygeodesy should be, empty. This causes import errors.

I was assuming that this situation would remain for some time, which is why I proposed printing a friendly error when the import fails. The error could hint someone at using the `--recursive` flag.

However, since this is so temporary, I think it does not make sense to spend time on this.

**Comment by GliderGeek** [comment]
currently [on pypi](https://pypi.python.org/pypi/PyGeodesy/17.4.8) :)
implementation is planned in issue #97
