### ISSUE TITLE
analysis breaks aat

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#99]
http://www.soaringspot.com/en_gb/zomerwedstrijden-2015-malden-2015/results/open-klasse/task-4-on-2015-07-22/daily

breaks at third flight. 3 people completed the entire task, so it might be related to outlandings

**Comment by roeles** [comment]
When branching, add a unit test for it, if it not already exists.

**Comment by GliderGeek** [comment]
i am not sure if i want to add an analysis to the test suite everytime a bug is found. a single analysis takes a lot of time (downloading and analyzing) and i dont want to wait 10 minutes everytime after i push to the repo to know if i have introduced a possible error.
instead, i could make a specific test covering the source of the bug. this makes a lot more sense to me.

**Comment by roeles** [comment]
Yeah, I can imagine.
A few thoughts:
- You could look into testing multiple scenarios concurrently. Gitlab supports that, and I think Travis also has multiple CPUs available.
- You might want to be able to test a single file. Not sure if you already can.

Also: while on the one hand waiting 10 minutes is a pain, it's less pain than shipping binaries with errors :)

**Comment by GliderGeek** [comment]
i completely agree with your last statement, although i differ in opinion on how to get there ;)
testing on a single file is an option, but i think i would like to go a step further and add unit tests on a more fundamental level.

let's say there is a bug in task definitions in the igc file
i could take this parts of the igc file (a few lines) and run these over the function which should extract the task information. this only tests the functionality that is broken and therefore also more clearly shows what needs to be fixed when the test fails.

if the bug appears on a higher level of a complete competition day (for instance when all pilots land out), there is maybe no other way than to run the complete analysis.

**Comment by GliderGeek** [comment]
problem comes from faulty B-record in igc file:

```
B1124065148041N00551156EA0096200988000060000000
B1124105148117N00551246EA0095800986000064000000
B1124145148194N00551327EA0095900988000064000000
B1124185148269N9833N00553309EA0084800873000068000000
B1125475149930N00553333EA0084400873000068000000
B1125515150023N00553340EA0084300872000064000000
B1125555150115N00553342EA0083800865000060000000
```

`5148269N9833N00553309E` is an invalid latitude-longitude string

**Comment by GliderGeek** [comment]
this will be solved when switching to aerofiles igc reader
this reader is able to ensure that the b-records are valid

**Comment by GliderGeek** [comment]
has been fixed in commit https://github.com/GliderGeek/opensoar/commit/d9366c101564d099cbf675b37d4df7b485002ad7
